
CREATE TABLE IF NOT EXISTS product (
	id BIGINT generated by default as identity,
	name VARCHAR(255) NOT NULL,
	picture_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS product_info (
	product_id BIGINT NOT NULL,
	name VARCHAR(255) NOT NULL,
	price DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS orders (
	id BIGINT generated by default as identity,	
	status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS orders_date (
	order_id BIGINT NOT NULL,
	status VARCHAR(255),
	date_created DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS order_product (
	quantity INT NOT NULL,
	order_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL
);